apiVersion: apps/v1
kind: Deployment
metadata:
  name: tse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tse
  template:
    metadata:
      labels:
        app: tse
    spec:
      containers:
      - image: okteto.dev/tse:latest
        name: tse
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "1bc48ffd-a6a7-4377-bdf7-796d0af9cbd3"
        - name: Vless_Path
          value: "/vlyde"
        - name: Vmess_UUID
          value: "1bc48ffd-a6a7-4377-bdf7-796d0af9cbd3"
        - name: Vmess_Path
          value: "/vmkhy"
        - name: Share_Path
          value: "/v2link"
